// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZbtCfnUGsTBo2BLdEDyRyFHLfeYjYRo',
    appId: '1:247540101456:web:9afb251d5589ae6ba1bc55',
    messagingSenderId: '247540101456',
    projectId: 'expense-tracker-c7b0d',
    authDomain: 'expense-tracker-c7b0d.firebaseapp.com',
    storageBucket: 'expense-tracker-c7b0d.firebasestorage.app',
    measurementId: 'G-7QWBT4MRQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07a2MJbhfBKiGi9Q-r2PN-70KRHs4FmE',
    appId: '1:247540101456:android:950b19e16b4fe9f3a1bc55',
    messagingSenderId: '247540101456',
    projectId: 'expense-tracker-c7b0d',
    storageBucket: 'expense-tracker-c7b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiuX61OBksNLycT0f9HdbpomAWVvSiDo',
    appId: '1:247540101456:ios:e1d822d13a8efd51a1bc55',
    messagingSenderId: '247540101456',
    projectId: 'expense-tracker-c7b0d',
    storageBucket: 'expense-tracker-c7b0d.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiuX61OBksNLycT0f9HdbpomAWVvSiDo',
    appId: '1:247540101456:ios:e1d822d13a8efd51a1bc55',
    messagingSenderId: '247540101456',
    projectId: 'expense-tracker-c7b0d',
    storageBucket: 'expense-tracker-c7b0d.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZbtCfnUGsTBo2BLdEDyRyFHLfeYjYRo',
    appId: '1:247540101456:web:6f413d7ba939069aa1bc55',
    messagingSenderId: '247540101456',
    projectId: 'expense-tracker-c7b0d',
    authDomain: 'expense-tracker-c7b0d.firebaseapp.com',
    storageBucket: 'expense-tracker-c7b0d.firebasestorage.app',
    measurementId: 'G-8QM5L8TXV3',
  );
}
